config/routes.rb
YourSecretary::Application.routes.draw do

  resources :haiku_searches, :only=>[:index,:show,:new,:update,:edit,:create,:destroy] do
    post :search, :on=>:collection
  end

  resources :haikus

  resources :tweets

  get "my_page/index"

  resources :tasks
  resources :books, :only=>[:show,:edit,:update,:destroy]
  resources :users,:only=>[:edit,:show,:update]
  resources :my_page ,:only=>[:index] do
    get :my_tweets, :on=>:collection
  end

  match "auth/:provider/callback"=> "sessions#create"
  match "auth/logout"=> "sessions#destory"
  resources :secretaries,:only=>[:index,:show,:new,:create,:edit,:update,:destroy]
  match "mo/sessions"=> "mo/sessions#index"
  match "smt/sessions"=> "smt/sessions#index"
  match "smt/secretaries"=> "smt/secretaries#index"
  match "smt/secretaries/new"=> "smt/secretaries#new"
  match "smt/my_page"=> "smt/my_page#index"
  match "smt/my_page/my_tweets"=> "smt/my_page#my_tweets"
  

  root :to => "secretaries#index"

end

app/models/haiku_search.rb
class HaikuSearch < ActiveGroonga::Base
end

app/controllers/haiku_searches_controller.rb
class HaikuSearchesController < ApplicationController
  # GET /haiku_searches
  # GET /haiku_searches.xml
  def index
    @haiku_searches = HaikuSearch.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @haiku_searches }
    end
  end
  
  # search 
  def search
    @keyword = params[:keyword]
    @result_set = HaikuSearch.select(:sentence=>@keyword)
  end  

  # GET /haiku_searches/1
  # GET /haiku_searches/1.xml
  def show
    @haiku_search = HaikuSearch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @haiku_search }
    end
  end

  # GET /haiku_searches/new
  # GET /haiku_searches/new.xml
  def new
    @haiku_search = HaikuSearch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @haiku_search }
    end
  end

  # GET /haiku_searches/1/edit
  def edit
    @haiku_search = HaikuSearch.find(params[:id])
  end

  # POST /haiku_searches
  # POST /haiku_searches.xml
  def create
    @haiku_search = HaikuSearch.new(params[:haiku_search])

    respond_to do |format|
      if @haiku_search.save
        format.html { redirect_to(@haiku_search, :notice => 'Haiku search was successfully created.') }
        format.xml  { render :xml => @haiku_search, :status => :created, :location => @haiku_search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @haiku_search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /haiku_searches/1
  # PUT /haiku_searches/1.xml
  def update
    @haiku_search = HaikuSearch.find(params[:id])

    respond_to do |format|
      if @haiku_search.update_attributes(params[:haiku_search])
        format.html { redirect_to(@haiku_search, :notice => 'Haiku search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @haiku_search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /haiku_searches/1
  # DELETE /haiku_searches/1.xml
  def destroy
    @haiku_search = HaikuSearch.find(params[:id])
    @haiku_search.destroy

    respond_to do |format|
      format.html { redirect_to(haiku_searches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/haiku_searches_helper.rb
module HaikuSearchesHelper
end

app/views/haiku_searches/_form.html.erb
<%= form_for(@haiku_search) do |f| %>
  <% if @haiku_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@haiku_search.errors.count, "error") %> prohibited this haiku_search from being saved:</h2>

      <ul>
      <% @haiku_search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_field :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/haiku_searches/edit.html.erb
<h1>Editing haiku_search</h1>

<%= render 'form' %>

<%= link_to 'Show', @haiku_search %> |
<%= link_to 'Back', haiku_searches_path %>

app/views/haiku_searches/index.html.erb
<h1>俳句の検索</h1>
<%= form_tag :controller=>'haiku_searches' ,:action=>'search' do  %>
  <div class="field">
    Word:
    <%= text_field_tag :keyword %>
  </div>
  <div class="actions">
    <%= submit_tag '検索' %>
  </div>
<% end %>

<h2>結果</h2>

<table>
  <tr>
    <th>Sentence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @haiku_searches.each do |haiku_search| %>
  <tr>
    <td><%= haiku_search.sentence %></td>
    <td><%= link_to 'Show', haiku_search %></td>
    <td><%= link_to 'Edit', edit_haiku_search_path(haiku_search) %></td>
    <td><%= link_to 'Destroy', haiku_search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Haiku search', new_haiku_search_path %>

app/views/haiku_searches/new.html.erb
<h1>New haiku_search</h1>

<%= render 'form' %>

<%= link_to 'Back', haiku_searches_path %>

app/views/haiku_searches/search.html.erb
<h1>俳句の検索</h1>
<%= form_tag :controller=>'haiku_searches' ,:action=>'search' do  %>
  <div class="field">
    Word:
    <%= text_field_tag :keyword %>
  </div>
  <div class="actions">
    <%= submit_tag '検索' %>
  </div>
<% end %>


<h1>検索結果一覧</h1>
検査ワードは？？：<%=@keyword %>
<br>
<table>
  <tr>
    <th>本文</th>
    <th></th>
    <th></th>
  </tr>

<% @result_set.each do |haiku_search| %>
  <tr>
    <td><%= haiku_search.sentence %></td>
    <td><%= link_to 'Show', haiku_search %></td>
    <td><%= link_to 'Destroy', haiku_search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Haiku search', new_haiku_search_path %>

app/views/haiku_searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sentence:</b>
  <%= @haiku_search.sentence %>
</p>


<%= link_to 'Edit', edit_haiku_search_path(@haiku_search) %> |
<%= link_to 'Back', haiku_searches_path %>