config/routes.rb
YourSecretary::Application.routes.draw do

  resources :haiku_searches, :only=>[:index,:show,:new,:update,:edit,:create,:destroy] do
    post :search, :on=>:collection
  end

  resources :haikus

  resources :tweets

  get "my_page/index"

  resources :tasks
  resources :books, :only=>[:show,:edit,:update,:destroy]
  resources :users,:only=>[:edit,:show,:update]
  resources :my_page ,:only=>[:index] do
    get :my_tweets, :on=>:collection
  end

  match "auth/:provider/callback"=> "sessions#create"
  match "auth/logout"=> "sessions#destory"
  resources :secretaries,:only=>[:index,:show,:new,:create,:edit,:update,:destroy]
  match "mo/sessions"=> "mo/sessions#index"
  match "smt/sessions"=> "smt/sessions#index"
  match "smt/secretaries"=> "smt/secretaries#index"
  match "smt/secretaries/new"=> "smt/secretaries#new"
  match "smt/my_page"=> "smt/my_page#index"
  match "smt/my_page/my_tweets"=> "smt/my_page#my_tweets"
  

  root :to => "secretaries#index"

end

app/models/haiku.rb
class Haiku < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence=>true
  validates :sentence, :presence=>true

end

app/controllers/haikus_controller.rb
require 'rubygems'
require 'groonga'

class HaikusController <  AbstractPcController
  layout "haiku"
  # GET /haikus
  # GET /haikus.xml
  def index
    @current_user = current_user
    #@haikus = Haiku.all
    @haikus = Haiku.joins(:user).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @haikus }
    end
  end

  # GET /haikus/1
  # GET /haikus/1.xml
  def show
    @haiku = Haiku.find(params[:id])
    @current_user = current_user
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @haiku }
    end
  end

  # GET /haikus/new
  # GET /haikus/new.xml
  def new
    @haiku = Haiku.new
    @current_user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @haiku }
    end
  end

  # GET /haikus/1/edit
  def edit
    @current_user = current_user
    @haiku = Haiku.find(params[:id])
  end

  # POST /haikus
  # POST /haikus.xml
  def create
    @current_user = current_user
    @haiku = Haiku.new(params[:haiku])
    @haiku.user_id=@current_user.id
    @haiku_search=HaikuSearch.new
    @haiku_search.sentence=params[:haiku][:sentence]
    respond_to do |format|
      if @haiku.save && @haiku_search.save
        @haiku_search.save
        format.html { redirect_to(@haiku, :notice => 'Haiku was successfully created.') }
        format.xml  { render :xml => @haiku, :status => :created, :location => @haiku }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @haiku.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /haikus/1
  # PUT /haikus/1.xml
  def update
    @current_user = current_user
    @haiku = Haiku.find(params[:id])

    respond_to do |format|
      if @haiku.update_attributes(params[:haiku])
        format.html { redirect_to(@haiku, :notice => 'Haiku was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @haiku.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /haikus/1
  # DELETE /haikus/1.xml
  def destroy
    @current_user = current_user
    @haiku = Haiku.find(params[:id])
    @haiku.destroy

    respond_to do |format|
      format.html { redirect_to(haikus_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/haikus_helper.rb
#:conding utf-8

module HaikusHelper
end

app/views/haikus/_form.html.erb
<%= form_for(@haiku) do |f| %>
  <% if @haiku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@haiku.errors.count, "error") %> prohibited this haiku from being saved:</h2>

      <ul>
      <% @haiku.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_area :sentence %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/haikus/edit.html.erb
<h1>Editing haiku</h1>

<%= render 'form' %>

<%= link_to 'Show', @haiku %> |
<%= link_to 'Back', haikus_path %>

app/views/haikus/index.html.erb
<br>
<%= link_to '俳句を書く', new_haiku_path %>|
 <%=link_to '俳句を検索する',:controller=>'haiku_searches' %>
<br><br>
<table class="haiku_table">
  <tr class="list_menu">
    <th class="haiku_td">タイトル</th>
    <th class="haiku_td">著者</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @haikus.each do |haiku| %>
  <tr　>
    <td><%= haiku.title %></td>
    <td><%= haiku.user.name %></td>
    <td><%= link_to 'Show', haiku %></td>
    <td><%= link_to 'Edit', edit_haiku_path(haiku) %></td>
    <td><%= link_to 'Destroy', haiku, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/haikus/new.html.erb
<h1>New haiku</h1>

<%= render 'form' %>

<%= link_to 'Back', haikus_path %>

app/views/haikus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @haiku.title %>
</p>

<p>
  <b>Sentence:</b>
  <%= @haiku.sentence %>
</p>

<p>
  <b>User:</b>
  <%= @haiku.user_id %>
</p>

<p>
  <b>Point:</b>
  <%= @haiku.point %>
</p>


<%= link_to 'Edit', edit_haiku_path(@haiku) %> |
<%= link_to 'Back', haikus_path %>