config/routes.rb
YourSecretary::Application.routes.draw do

  resources :haiku_searches, :only=>[:index,:show,:new,:update,:edit,:create,:destroy] do
    post :search, :on=>:collection
  end

  resources :haikus

  resources :tweets

  get "my_page/index"

  resources :tasks
  resources :books, :only=>[:show,:edit,:update,:destroy]
  resources :users,:only=>[:edit,:show,:update]
  resources :my_page ,:only=>[:index] do
    get :my_tweets, :on=>:collection
  end

  match "auth/:provider/callback"=> "sessions#create"
  match "auth/logout"=> "sessions#destory"
  resources :secretaries,:only=>[:index,:show,:new,:create,:edit,:update,:destroy]
  match "mo/sessions"=> "mo/sessions#index"
  match "smt/sessions"=> "smt/sessions#index"
  match "smt/secretaries"=> "smt/secretaries#index"
  match "smt/secretaries/new"=> "smt/secretaries#new"
  match "smt/my_page"=> "smt/my_page#index"
  match "smt/my_page/my_tweets"=> "smt/my_page#my_tweets"
  

  root :to => "secretaries#index"

end

app/controllers/my_page_controller.rb
#coding: utf-8

require'rubygems'
require 'twitter'

class MyPageController < AbstractPcController
  ssl_allowed :index,:my_tweets

  helper_method :index_action?

  def index
    @user = current_user
    @my_books=Rails.cache.read('MY_BOOKS')
    if @my_books == nil
      @my_books=Book.where('user_id=?',@user.id).latest.paginate(:page => params[:page], :per_page => 5)
      Rails.cache.write('MY_BOOKS',@my_books)
    end
    @my_schedule=Schedule.where('user_id=?',@user.id).latest.paginate(:page => params[:page], :per_page => 5)
    @my_tasks ||=Task.where('user_id=?',@user.id).latest.paginate(:page=>params[:pgae],:per_page=>5)
    MyTweets.tweet_analyze_for_user @user
    @secretary_message=MyTweets.alert_tweet @user,'ツブヤキを解析してデータ登録を'
    respond_to do |format|
      format.html
    end
  end

  def my_tweets
    @user = current_user
    #@client=Twitter::Client.new
    Twitter::Client.configure do |config|
      config.oauth_consumer_token='cxhImnAeGuuJDKESgvmqQ'
      config.oauth_consumer_secret='lqIOiWjPxrJ1lpF7zOe6H0PwG1vlPX9G8RkGvUDAGI'
    end
    @client=Twitter::Client.new :oauth_access=> {
      :key=>@user.token,
      :secret=>@user.secret
    }
    @user_timelines = @client.timeline_for(:user, :id =>@user.name, :count=>10)
    MyTweets.tweet_analyze_for_user @user
    flash[:now]=MyTweets.alert_tweet @user,'ツブヤキを解析してデータ登録を'
  end
 
  def index_action?
    if action_name.eql?("index")
      true
    else
      false
    end
  end

end

app/controllers/smt/my_page_controller.rb
class Smt::MyPageController < AbstractSmtController
  def index
  end

  def my_tweets

  end

end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/helpers/smt/my_page_helper.rb
module Smt::MyPageHelper
end

app/views/my_page/index.html.erb
<h1>マイページ</h1>
<hr>
  <p id="notice"><%= notice %></p>
<h2>本一覧</h2>
<div id="my_book_list">
<%= will_paginate @my_books, :prev_label=>'«前', :next_label=>'次»'   %>
<table class="mypage_table">
  <tr class="list_menu">
    <th>タイトル</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @my_books.each do |book| %>
  <tr >
    <td><%= book.title %></td>
    <td><%= link_to '詳細を見る', book %></td>
    <td><%= link_to '編集する', edit_book_path(book) %></td>
    <td><%= link_to '削除する', book, :confirm => '本当に?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br>
  <hr>
<h2>予定一覧</h2>
<div id="my_schedule_list">
<%= will_paginate @my_schedule, :prev_label=>'«前', :next_label=>'次»'  %>
<table class="mypage_table" >
  <tr class="list_menu">
    <th>タイトル</th>
    <th>日付</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% for schedule in @my_schedule %>
    <%= will_paginate @my_schedule, :prev_label=>'«前', :next_label=>'次»'  %>
    <tr>
      <td><%=schedule.title %></td>
      <td><%=schedule.date %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
</table>
</div>
<br>
<h2>タスク一覧</h2>
<div id="my_task_list">
<table class="mypage_table">
  <tr class="list_menu">
    <th>タスク名</th>
    <th>重要度</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @my_tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.priority %></td>
    <td><%= link_to '詳細を見る', task %></td>
    <td><%= link_to '編集する', edit_task_path(task) %></td>
    <td><%= link_to '削除する', task, :confirm => '削除するならTwitterの方を先にお願い！', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

app/views/my_page/my_tweets.html.erb
<p id="notice"><%= notice %></p>
<table class="mypage_table">
  <tr class="list_menu">
    <th></th>
    <th>名前</th>
    <th>ツイート</th>
  </tr>

<% @user_timelines.each do |timeline| %>
  <tr >
     <td><%= timeline.user.id %></td>
    <td><%= timeline.user.screen_name %></td>
    <td><%= timeline.text %></td>
  </tr>
<% end %>
</table>